site_name: SimcirHW - Documentação
site_description: SimcirJS com integração com hardware baseado na tecnologia NodeMCU.
repo_url: https://github.com/diegocardoso93/SimcirHW

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
#extra_css:
#- css/extra.css
#extra_javascript:
#- js/extra.js

site_favicon: img/favicon.png

pages:
- 'Início': '00inicio.md'
- Tutorial:
    - 'Início': '10requisitos.md'
    - 'Instalação': '11instalacao.md'
- Documentação:
    - Home: 'blank.md'
