sudo: required # due to manual install of make 4.1
dist: trusty # due to the make 4.1 not installable on precise
language: cpp
# we need at least GNU Make 4.0, which isn't available in trusty, so grab it
# manually from xenial
before_install:
- wget http://mirrors.kernel.org/ubuntu/pool/main/m/make-dfsg/make_4.1-6_amd64.deb
- sudo dpkg -i make_4.1-6_amd64.deb
addons:
  apt:
    packages:
    - python-serial
    - gperf
# note that we clobber $PATH completely, to get rid of /opt/python* stuff so
# we can use the system python and python-serial, rather than messing around
# with pip all over the place
install:
  - export PATH=$PWD/tools/toolchains/esp8266/bin:$PWD/tools/toolchains/esp32/bin:/bin:/usr/bin:/sbin:/usr/sbin
script:
- export BUILD_DATE=$(date +%Y%m%d)
- env BUILD_DIR_BASE=`pwd`/build/float make MORE_CFLAGS="-DBUILD_DATE='\"'$BUILD_DATE'\"'" defconfig all
- env BUILD_DIR_BASE=`pwd`/build/integer make MORE_CFLAGS="-DLUA_NUMBER_INTEGRAL -DBUILD_DATE='\"'$BUILD_DATE'\"'" defconfig all
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
#- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/pr-build.sh; fi
