site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: true

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

site_favicon: img/favicon.png

pages:
- Overview: 'index.md'
- English:
    - Building the firmware: 'en/build.md'
    - Flashing the firmware: 'en/flash.md'
    - Filesystem on SD card: 'en/sdcard.md'
    - Uploading code: 'en/upload.md'
    - FAQs:
        - Lua Developer FAQ: 'en/lua-developer-faq.md'
        - Extension Developer FAQ: 'en/extn-developer-faq.md'
    - Support: 'en/support.md'
    - Modules:
        - 'adc':          'en/modules/adc.md'
        - 'bit':          'en/modules/bit.md'
        - 'bthci':        'en/modules/bthci.md'
        - 'can':          'en/modules/can.md'
        - 'dht':          'en/modules/dht.md'
        - 'file':         'en/modules/file.md'
        - 'gpio':         'en/modules/gpio.md'
        - 'i2c':          'en/modules/i2c.md'
        - 'ledc':         'en/modules/ledc.md'
        - 'net':          'en/modules/net.md'
        - 'node':         'en/modules/node.md'
        - 'ow (1-Wire)':  'en/modules/ow.md'
        - 'sdmmc':        'en/modules/sdmmc.md'
        - 'sigma delta':  'en/modules/sigma-delta.md'
        - 'spi':          'en/modules/spi.md'
        - 'struct':       'en/modules/struct.md'
        - 'tmr':          'en/modules/tmr.md'
        - 'u8g2':         'en/modules/u8g2.md'
        - 'u8g2 Display': 'en/modules/u8g2_disp.md'
        - 'uart':         'en/modules/uart.md'
        - 'wifi':         'en/modules/wifi.md'
        - 'ws2812':       'en/modules/ws2812.md'
